### ISSUE TITLE
Option in model.add_joint with JointType.SPHERICAL

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/bioNC#76]
In the following adding of a joint is it possible to add the option ground_application point to be able to construct a spherical joint not exclusively at the rd point of the proximal segment ? 
to have : 
```python 
    model.add_joint(
        name="left_hip",
        joint_type=JointType.SPHERICAL,
        ground_application_point=left_hip_joint,
        parent="PELVIS",
        child="LTHIGH",)
```
Instead of this : 

```python 
    model.add_joint(
        name="left_hip",
        joint_type=JointType.SPHERICAL,
        parent="PELVIS",
        child="LTHIGH",)
```

But maybe I missed something (i have adapted the function in the repertory bionc \examples\model_creation to test it on true data and see the results)

**Comment by Ipuch** [comment]
Yes, it's possible there is a  joint called JointType.GROUND_SPHERICAL, I think so.

If not we need to create it 😀

**Comment by Ipuch** [comment]
Okay I understood what you want.

I was proposing the wrong feature.

It should look like this:

```python3
model.add_joint(
        name="left_hip",
        joint_type=JointType.SPHERICAL,
        parent="PELVIS",
        child="LTHIGH",
        parent_application_point="LEFT_HIP",
        child_application_point="HIP_CENTER",
)
```

**Comment by ANaaim** [comment]
I am currently doing it.

**Comment by Ipuch** [comment]
Yes,

Constantlength is the perfect exemple,

If you don't specify the parent an child locations it take the proximal and distal points.

All joints should behave like this.

There is no need of creating a new class. Please modify consequently the existing Spherical class.

I wrote it the last detailed post previously.


If you started to do it don't hesitate to open the pull request. Because if you ask more question it means you require a review of what you wrote.

**Comment by ANaaim** [comment]
Ok, i thought i should open it when it was fully functional. 

Currently, I have done a new class completely ==> i will modify in futur commit

**Comment by ANaaim** [comment]
Can we close this ?
