### ISSUE TITLE
Add a function to export the natural coordinate and associated value in a c3d files 

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/bioNC#94]
This c3d should contain : 
- [x] Everything that was in the initial c3d 
- [x] The Q value after the optimisation process
- [x] The technical marker associated with the Q post optim
- [ ] Kinematics calcultad for all the different joint in the model.
- [ ] Maybe in the metadata all the additional information on the joint used in the model, any parameters 

Different aim in this function : 

- Could replace the visualisation in bioviz for controlling data and using any c3d reader such as Mokka.  
- Have a file that could be analysed without using bioNC for example for people not very used to using code it would only be needed to program them a c3d reader to extract the data. 

(That it is clearly inspired fro what it is done in any gait analysis software).

Any comment, comment, or opignon on this ?

**Comment by Ipuch** [comment]
I understand the need for a classic habit to store everything in c3d to display it using Mokka.

If you want my full opinion. Here it is. To me it makes no sens to store joint angles or Q and even model location in c3d. Because they are indented to store experimental data and the mentioned data is the fruit of numerical computations.

The true problem comes from the fact we don't have yet a cross plateform mokka that can be launched from any language...

So we have to rely in hacky way on mokka.

I understand nonetheless the benefits of storing everything in a c3d because it is cross language kind of a standard.

But otherwise why not juste store the solution dictionary into a pickle? 

Practically, this would mean include a saving method in the IK class.

So that is looks like 

Ik.save_as_c3d("somewhere in your floppy disk")

**Comment by Ipuch** [comment]
Answered in #111
